.PHONY: clean all

all: collatz01 collatz02 collatz03 collatz04 collatz05

collatz01: collatz01.c collatz.h
	gcc collatz01.c -o collatz01

collatz02: collatz02.c collatz.h
	gcc collatz02.c -o collatz02

collatz03: collatz03.c collatz.h
	gcc collatz03.c -o collatz03

collatz04: collatz04.c collatz.h
	gcc collatz04.c -o collatz04

collatz05: collatz05.c collatz.h
	gcc collatz05.c -o collatz05

clean:
	rm -f collatz0? collatz0?.o *~

